import config
from pathlib import Path
from utils_gradients import train_resnet_with_gradients
                
train_resnet_with_gradients(batch_size=1,
             checkpoints_folder=config.args.checkpoints_folder,
             classes=config.classes,
             color_jitter_brightness=config.args.color_jitter_brightness,
             color_jitter_contrast=config.args.color_jitter_contrast,
             color_jitter_hue=config.args.color_jitter_hue,
             color_jitter_saturation=config.args.color_jitter_saturation,
             device=config.device,
             learning_rate=config.args.learning_rate,
             learning_rate_decay=config.args.learning_rate_decay,
             log_csv=config.log_csv,
             train_order_csv=config.train_order_csv,
             num_classes=config.num_classes,
             num_layers=18,
             num_workers=config.args.num_workers,
             path_mean=config.path_mean,
             path_std=config.path_std,
             pretrain=False,
             resume_checkpoint=True,
            #  resume_checkpoint_path=Path("/home/brenta/scratch/jason/checkpoints/image_net/vanilla/exp_36/resnet50_e0_mb60000_va0.74241.pt"),
             resume_checkpoint_path=Path("/home/brenta/scratch/jason/checkpoints/image_net/vanilla/exp_10/resnet18_e0_mb40000_va0.80428.pt"),
             save_interval=config.args.save_interval,
             num_epochs=config.args.num_epochs,
            #  train_folder=Path("/home/ifsdata/vlg/jason/easy-self-supervised-training/data/voc_trainval_full"),
             train_folder=Path("/home/brenta/scratch/data/imagenet_rotnet/"),
             weight_decay=config.args.weight_decay)

# train_resnet_with_gradients(batch_size=1,
#              checkpoints_folder=config.args.checkpoints_folder,
#              classes=config.classes,
#              color_jitter_brightness=config.args.color_jitter_brightness,
#              color_jitter_contrast=config.args.color_jitter_contrast,
#              color_jitter_hue=config.args.color_jitter_hue,
#              color_jitter_saturation=config.args.color_jitter_saturation,
#              device=config.device,
#              learning_rate=config.args.learning_rate,
#              learning_rate_decay=config.args.learning_rate_decay,
#              log_csv=config.log_csv,
#              train_order_csv=config.train_order_csv,
#              num_classes=config.num_classes,
#              num_layers=config.args.num_layers,
#              num_workers=config.args.num_workers,
#              path_mean=config.path_mean,
#              path_std=config.path_std,
#              pretrain=False,
#              resume_checkpoint=True,
#              resume_checkpoint_path=Path("/home/brenta/scratch/jason/checkpoints/image_net/vanilla/exp_10/resnet18_e0_mb10000_va0.70834.pt"),
#              save_interval=config.args.save_interval,
#              num_epochs=config.args.num_epochs,
#              train_folder=Path("/home/ifsdata/vlg/jason/easy-self-supervised-training/data/voc_trainval_full"),
#              weight_decay=config.args.weight_decay)